version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/1-express-request-logging/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/2-express-morgan/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/3-express-error-handling/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/4-uncaught-exception/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/5-unhandled-promise-rejection/'
    schedule:
      interval: 'daily'
